# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/zigbee/esp_zigbee_gateway:
  disable:
    - if: IDF_TARGET == "esp32c2" or IDF_TARGET == "esp32c6"
      temporary: true
      reason: target(s) not supported yet

examples/zigbee/esp_zigbee_rcp:
  enable:
    - if: IDF_TARGET == "esp32h4"
      reason: should able to run on esp32h4

examples/zigbee/light_sample:
  enable:
    - if: IDF_TARGET == "esp32h4"
      reason: should able to run on esp32h4
